image: "noticeeverything/pipelines:latest"

stages:
  - build
  - test
  - deploy

# to cache Cypress binary we use environment variables
# to point at the folders we can list as paths in "cache" job settings
variables:
  CYPRESS_CACHE_FOLDER: "$CI_PROJECT_DIR/cache/Cypress"

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/
    - .yarn
    - cache/Cypress

install:
  stage: build
  script:
    # this directory doesn't exist by default - likely has to do with how Gitlab clones the repo
    # without this directory, transcrypt fails
    - mkdir .git/hooks
    - transcrypt -c $TRANSCRYPT_CIPHER -p $TRANSCRYPT_KEY -y
    - yarn install --pure-lockfile --cache-folder .yarn

# Test/lint all branches except master
test:
  stage: test
  except:
    - master
  script:
    - yarn lint
    - yarn test.ci
    - yarn e2e.ci

# Only deploy master
deploy:
  stage: deploy
#  only:
#    - master
  before_script:
    - mkdir -p ~/.ssh
    - echo -e "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  script:
    - export TAG=$CI_COMMIT_REF_SLUG-prod-latest
    - yarn deploy --env=prod --awsRegion=$AWS_DEFAULT_REGION --tag=$TAG
